openapi: 3.0.0
info:
  title: Trigger Event API
  description: |
    API zum Auslösen von ausgehenden Prozessen in der MACO APP | API for triggering outbound maco processes in the MACO APP

    <details>
    <summary>Changelog</summary>

    **Version 1.0.1** - *08. August 2024* - _Autor: DAS_

    - Erweiterung der API um zusätzliche Schemas und Beispiele.
    - Hinzugefügte Schemas: `START_LIEFERBEGINN_STROM`, `START_LIEFERBEGINN_GAS`, `START_ABR_NN`, `START_DEFINITION_SCHALTZEIT`, `START_DEFINITION_LEISTUNGSKURVE`, `START_DEFINITION_ZAEHLZEIT`, `START_KUENDIGUNG`.

    **Version 1.0.0** - *01. August 2024* - _Autor: DAS_

    - Initiale Veröffentlichung der API mit dem `START_SPERRAUFTRAG`-Schema.

    </details>
  version: 1.0.1
servers:
  - url: https://api.macoapp.de
    description: Fake Env
tags:
  - name: SLIM EVENTS
    description: Trigger Event mit Angabe vom Typ und einer BelegId, mit der Daten im ERP nachgelesen werden können. | Trigger event with specification of the type and a document ID where data can be read in the backend.
  - name: EXTENDED EVENTS
    description: | 
      Trigger Events, die alle notwendigen Informationen enthalten, ohne Daten nachlesen zu müssen. | Trigger events that contain all necessary information.
      *Die erweiterten Events dokumentieren welche Parameter ein Event eines bestimmten Type enthalten kann und mindestens muss* | *The extended events document which parameters an event of a certain type can and at least must contain.*
paths:
  /START_LIEFERBEGINN:
    post:
      summary: START_LIEFERBEGINN
      deprecated: false
      description: Erhalte Event vom Backend | Receive Event From Backend
      operationId: START_LIEFERBEGINN
      tags: 
        - SLIM EVENTS
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/START_LIEFERBEGINN'
      responses:
        '201':
          description: Erfolg | Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  businessKey:
                    type: string
                    format: uuid
                    description: Einzigartige Kennung des Geschäftsprozesses | Unique identifier of the business process
                  message:
                    type: string
                    example: "received event START_LIEFERBEGINN_STROM with id at 2024-08-08T12:58:22Z and started process with businessKey 4c7170ed-3518-41ee-8582-39ab65b00107"
                    description: Nachricht mit Details zum ausgelösten Event | Message with details about the triggered event
                required:
                  - businessKey
                  - message
      security: []
  /START_KUENDIGUNG:
    post:
      summary: START_KUENDIGUNG
      deprecated: false
      description: Erhalte Event vom Backend | Receive Event From Backend
      operationId: START_KUENDIGUNG
      tags: 
        - SLIM EVENTS
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/START_KUENDIGUNG'
      responses:
        '201':
          description: Erfolg | Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  businessKey:
                    type: string
                    format: uuid
                    description: Einzigartige Kennung des Geschäftsprozesses | Unique identifier of the business process
                  message:
                    type: string
                    example: "received event START_KUENDIGUNG_STROM with id at 2024-08-08T12:58:22Z and started process with businessKey 4c7170ed-3518-41ee-8582-39ab65b00107"
                    description: Nachricht mit Details zum ausgelösten Event | Message with details about the triggered event
                required:
                  - businessKey
                  - message
      security: []
  /AENDERUNG_AD:
    post:
      summary: AENDERUNG_AD
      deprecated: false
      description: Erhalte Event vom Backend | Receive Event From Backend
      operationId: AENDERUNG_AD
      tags: 
        - SLIM EVENTS
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AENDERUNG_AD'
      responses:
        '201':
          description: Erfolg | Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  businessKey:
                    type: string
                    format: uuid
                    description: Einzigartige Kennung des Geschäftsprozesses | Unique identifier of the business process
                  message:
                    type: string
                    example: "received event AENDERUNG_AD_STROM with id at 2024-08-08T12:58:22Z and started process with businessKey 4c7170ed-3518-41ee-8582-39ab65b00107"
                    description: Nachricht mit Details zum ausgelösten Event | Message with details about the triggered event
                required:
                  - businessKey
                  - message
      security: []
  /START_ENERGIEMENGE:
    post:
      summary: START_ENERGIEMENGE
      deprecated: false
      description: Erhalte Event vom Backend | Receive Event From Backend
      operationId: START_ENERGIEMENGE
      tags: 
        - SLIM EVENTS
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/START_ENERGIEMENGE'
      responses:
        '201':
          description: Erfolg | Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  businessKey:
                    type: string
                    format: uuid
                    description: Einzigartige Kennung des Geschäftsprozesses | Unique identifier of the business process
                  message:
                    type: string
                    example: "received event START_ENERGIEMENGE_STROM with id at 2024-08-08T12:58:22Z and started process with businessKey 4c7170ed-3518-41ee-8582-39ab65b00107"
                    description: Nachricht mit Details zum ausgelösten Event | Message with details about the triggered event
                required:
                  - businessKey
                  - message
      security: []
  /START_ZAEHLERSTAND:
    post:
      summary: START_ZAEHLERSTAND
      deprecated: false
      description: Erhalte Event vom Backend | Receive Event From Backend
      operationId: START_ZAEHLERSTAND
      tags: 
        - SLIM EVENTS
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/START_ZAEHLERSTAND'
      responses:
        '201':
          description: Erfolg | Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  businessKey:
                    type: string
                    format: uuid
                    description: Einzigartige Kennung des Geschäftsprozesses | Unique identifier of the business process
                  message:
                    type: string
                    example: "received event START_ZAEHLERSTAND_STROM with id at 2024-08-08T12:58:22Z and started process with businessKey 4c7170ed-3518-41ee-8582-39ab65b00107"
                    description: Nachricht mit Details zum ausgelösten Event | Message with details about the triggered event
                required:
                  - businessKey
                  - message
      security: []
  /START_LASTGANG:
    post:
      summary: START_LASTGANG
      deprecated: false
      description: Erhalte Event vom Backend | Receive Event From Backend
      operationId: START_LASTGANG
      tags: 
        - SLIM EVENTS
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/START_LASTGANG'
      responses:
        '201':
          description: Erfolg | Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  businessKey:
                    type: string
                    format: uuid
                    description: Einzigartige Kennung des Geschäftsprozesses | Unique identifier of the business process
                  message:
                    type: string
                    example: "received event START_LASTGANG_STROM with id at 2024-08-08T12:58:22Z and started process with businessKey 4c7170ed-3518-41ee-8582-39ab65b00107"
                    description: Nachricht mit Details zum ausgelösten Event | Message with details about the triggered event
                required:
                  - businessKey
                  - message
      security: []
  /START_PARTIN:
    post:
      summary: START_PARTIN
      deprecated: false
      description: Erhalte Event vom Backend | Receive Event From Backend
      operationId: START_PARTIN
      tags: 
        - SLIM EVENTS
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/START_PARTIN'
      responses:
        '201':
          description: Erfolg | Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  businessKey:
                    type: string
                    format: uuid
                    description: Einzigartige Kennung des Geschäftsprozesses | Unique identifier of the business process
                  message:
                    type: string
                    example: "received event START_PARTIN_STROM with id at 2024-08-08T12:58:22Z and started process with businessKey 4c7170ed-3518-41ee-8582-39ab65b00107"
                    description: Nachricht mit Details zum ausgelösten Event | Message with details about the triggered event
                required:
                  - businessKey
                  - message
      security: []
  /START_NACHRICHTENEINGANG:
    post:
      summary: START_NACHRICHTENEINGANG
      deprecated: false
      description: Erhalte Event vom Backend | Receive Event From Backend
      operationId: START_NACHRICHTENEINGANG
      tags: 
        - SLIM EVENTS
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/START_NACHRICHTENEINGANG'
      responses:
        '201':
          description: Erfolg | Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  businessKey:
                    type: string
                    format: uuid
                    description: Einzigartige Kennung des Geschäftsprozesses | Unique identifier of the business process
                  message:
                    type: string
                    example: "received event START_NACHRICHTENEINGANG_STROM with id at 2024-08-08T12:58:22Z and started process with businessKey 4c7170ed-3518-41ee-8582-39ab65b00107"
                    description: Nachricht mit Details zum ausgelösten Event | Message with details about the triggered event
                required:
                  - businessKey
                  - message
      security: []
  /inbound[SLIM]:
    post:
      summary: Trigger Events
      deprecated: false
      description: Erhalte Event vom Backend | Receive Event From Backend
      operationId: inboundSlim
      tags: 
        - SLIM EVENTS
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EVENT_MIT_BELEGID'
      responses:
        '201':
          description: Erfolg | Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  businessKey:
                    type: string
                    format: uuid
                    description: Einzigartige Kennung des Geschäftsprozesses | Unique identifier of the business process
                  message:
                    type: string
                    example: "received event START_LIEFERBEGINN_STROM with id at 2024-08-08T12:58:22Z and started process with businessKey 4c7170ed-3518-41ee-8582-39ab65b00107"
                    description: Nachricht mit Details zum ausgelösten Event | Message with details about the triggered event
                required:
                  - businessKey
                  - message
      security: []
  /inbound[EXTENDED]:
    post:
      summary: Trigger Events
      deprecated: false
      description: Erhalte Event vom Backend | Receive Event From Backend
      operationId: inbound
      tags: 
        - EXTENDED EVENTS
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/START_SPERRAUFTRAG'
                - $ref: '#/components/schemas/START_LIEFERBEGINN_STROM'
                - $ref: '#/components/schemas/START_LIEFERBEGINN_GAS'
                - $ref: '#/components/schemas/START_ABR_NN'
                - $ref: '#/components/schemas/START_DEFINITION_SCHALTZEIT'
                - $ref: '#/components/schemas/START_DEFINITION_LEISTUNGSKURVE'
                - $ref: '#/components/schemas/START_DEFINITION_ZAEHLZEIT'
                - $ref: '#/components/schemas/START_KUENDIGUNG'
            examples:
              START_SPERRAUFTRAG:
                $ref: '#/components/examples/START_SPERRAUFTRAG'
              START_LIEFERBEGINN_STROM:
                $ref: '#/components/examples/START_LIEFERBEGINN_STROM'
              START_LIEFERBEGINN_GAS:
                $ref: '#/components/examples/START_LIEFERBEGINN_GAS'
              START_ABR_NN:
                $ref: '#/components/examples/START_ABR_NN'
              START_DEFINITION_SCHALTZEIT:
                $ref: '#/components/examples/START_DEFINITION_SCHALTZEIT'
              START_DEFINITION_LEISTUNGSKURVE:
                $ref: '#/components/examples/START_DEFINITION_LEISTUNGSKURVE'
              START_DEFINITION_ZAEHLZEIT:
                $ref: '#/components/examples/START_DEFINITION_ZAEHLZEIT'
              START_KUENDIGUNG:
                $ref: '#/components/examples/START_KUENDIGUNG'
      responses:
        '201':
          description: Erfolg | Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  businessKey:
                    type: string
                    format: uuid
                    description: Einzigartige Kennung des Geschäftsprozesses | Unique identifier of the business process
                  message:
                    type: string
                    example: "received event START_LIEFERBEGINN_STROM with id at 2024-08-08T12:58:22Z and started process with businessKey 4c7170ed-3518-41ee-8582-39ab65b00107"
                    description: Nachricht mit Details zum ausgelösten Event | Message with details about the triggered event
                required:
                  - businessKey
                  - message
      security: []

components:
  schemas:
    START_SPERRAUFTRAG:
      type: object
      description: Schema zum Sperren einer Marktlokation | Schema for locking a market location
      properties:
        id:
          type: string
          description: BelegId des Datensatzes in der Tabelle im Backend | DocumentId of the data record in the table in the backend
          example: STARTSPERRAUFTRAG1
        eventName:
          type: string
          description: Name des Events | Name of the event
          example: START_SPERRAUFTRAG
          enum: 
            - START_SPERRAUFTRAG
        marktlokationsId:
          type: string
          description: Marktlokations-ID | Market location ID
          example: '50000083216'
        sparte:
          type: string
          description: Sparte, z.B. Strom oder Gas | Sector, e.g., electricity or gas
          example: STROM
        absender:
          type: string
          description: Rollencodenummer des Absenders | Role code number of the sender
          example: '9903790000002'
        empfaenger:
          type: string
          description: Rollencodenummer des Empfängers | Role code number of the recipient
          example: '9900321000005'
      required:
        - id, eventName, marktlokationsId, sparte, absender, empfaenger
    START_LIEFERBEGINN_STROM:
      type: object
      description: Schema zum Starten des Lieferbeginns für Strom | Schema for starting the delivery of electricity
      properties:
        id:
          type: string
          description: BelegId des Datensatzes in der Tabelle im Backend | DocumentId of the data record in the table in the backend
          example: 110000000408
        eventName:
          type: string
          description: Name des Events | Name of the event
          example: START_LIEFERBEGINN
        marktlokationsId:
          type: string
          description: Marktlokations-ID | Market location ID
          example: '50074561188'
        sparte:
          type: string
          description: Sparte, z.B. Strom | Sector, e.g., electricity
          example: STROM
        energierichtung:
          type: string
          description: Energierichtung, z.B. AUSSP | Energy direction, e.g., AUSSP
          example: AUSSP
        vertragsbeginn:
          type: string
          format: date-time
          description: Beginn des Vertrags | Start of the contract
          example: '2024-09-30T22:00:00Z'
        absender:
          type: string
          description: Rollencodenummer des Absenders | Role code number of the sender
          example: '9903790000002'
        empfaenger:
          type: string
          description: Rollencodenummer des Empfängers | Role code number of the recipient
          example: '9900321000005'
      required:
        - id, eventName, marktlokationsId, sparte, energierichtung, vertragsbeginn, absender, empfaenger
    START_LIEFERBEGINN_GAS:
      type: object
      description: Schema zum Starten des Lieferbeginns für Gas | Schema for starting the delivery of gas
      properties:
        id:
          type: string
          description: BelegId des Datensatzes in der Tabelle im Backend | DocumentId of the data record in the table in the backend
          example: 110000000611
        eventName:
          type: string
          description: Name des Events | Name of the event
          example: START_LIEFERBEGINN
        marktlokationsId:
          type: string
          description: Marktlokations-ID | Market location ID
          example: '50074561188'
        sparte:
          type: string
          description: Sparte, z.B. Gas | Sector, e.g., gas
          example: GAS
        vertragsbeginn:
          type: string
          format: date-time
          description: Beginn des Vertrags | Start of the contract
          example: '2024-06-01T04:00:00Z'
        absender:
          type: string
          description: Rollencodenummer des Absenders | Role code number of the sender
          example: '9800044300007'
        empfaenger:
          type: string
          description: Rollencodenummer des Empfängers | Role code number of the recipient
          example: '9870013800007'
      required:
        - id, eventName, marktlokationsId, sparte, vertragsbeginn, absender, empfaenger
    START_ABR_NN:
      type: object
      description: Schema zum Starten der Netznutzungsabrechnung | Schema for starting network usage billing
      properties:
        id:
          type: string
          description: BelegId des Datensatzes in der Tabelle im Backend | DocumentId of the data record in the table in the backend
          example: 110000000409
        eventName:
          type: string
          description: Name des Events | Name of the event
          example: START_ABR_NN
        marktlokationsId:
          type: string
          description: Marktlokations-ID | Market location ID
          example: '50074561188'
        sparte:
          type: string
          description: Sparte, z.B. Strom | Sector, e.g., electricity
          example: STROM
        artikelId:
          type: string
          description: Artikel-ID | Article ID
          example: '1-02-0-001'
        vertragsbeginn:
          type: string
          format: date-time
          description: Beginn des Vertrags | Start of the contract
          example: '2024-10-31T23:00:00Z'
        absender:
          type: string
          description: Rollencodenummer des Absenders | Role code number of the sender
          example: '9900321000005'
        empfaenger:
          type: string
          description: Rollencodenummer des Empfängers | Role code number of the recipient
          example: '9903790000002'
      required:
        - id, eventName, marktlokationsId, sparte, artikelId, vertragsbeginn, absender, empfaenger
    START_DEFINITION_SCHALTZEIT:
      type: object
      description: Schema zur Definition von Schaltzeiten | Schema for defining switching times
      properties:
        id:
          type: string
          description: BelegId des Datensatzes in der Tabelle im Backend | DocumentId of the data record in the table in the backend
          example: 110000000406
        eventName:
          type: string
          description: Name des Events | Name of the event
          example: START_DEFINITION_SCHALTZEIT
        code:
          type: string
          description: Code für die Schaltzeit | Code for the switching time
          example: AC
        beginndatum:
          type: string
          format: date-time
          description: Beginndatum der Schaltzeit | Start date of the switching time
          example: '2024-06-30T22:00:00Z'
        endedatum:
          type: string
          format: date-time
          description: Enddatum der Schaltzeit | End date of the switching time
          example: '2024-08-30T22:00:00Z'
        haeufigkeit:
          type: string
          description: Häufigkeit der Schaltzeit | Frequency of the switching time
          example: JAEHRLICH
        schalthandlung:
          type: string
          description: Art der Schalthandlung | Type of switching action
          example: LEISTUNG_AN
      required:
        - id, eventName, code, beginndatum, endedatum, haeufigkeit, schalthandlung
    START_DEFINITION_LEISTUNGSKURVE:
      type: object
      description: Schema zur Definition der Leistungskurve | Schema for defining the performance curve
      properties:
        id:
          type: string
          description: BelegId des Datensatzes in der Tabelle im Backend | DocumentId of the data record in the table in the backend
          example: 110000000405
        eventName:
          type: string
          description: Name des Events | Name of the event
          example: START_DEFINITION_LEISTUNGSKURVE
        code:
          type: string
          description: Code für die Leistungskurve | Code for the performance curve
          example: ABC
        beginndatum:
          type: string
          format: date-time
          description: Beginndatum der Leistungskurve | Start date of the performance curve
          example: '2024-06-30T22:00:00Z'
        endedatum:
          type: string
          format: date-time
          description: Enddatum der Leistungskurve | End date of the performance curve
          example: '2024-08-30T22:00:00Z'
        obererSchwellwert:
          type: number
          description: Oberer Schwellwert für die Leistungskurve | Upper threshold for the performance curve
          example: 50
      required:
        - id, eventName, code, beginndatum, endedatum, obererSchwellwert
    START_DEFINITION_ZAEHLZEIT:
      type: object
      description: Schema zur Definition der Zählzeit | Schema for defining the metering time
      properties:
        id:
          type: string
          description: BelegId des Datensatzes in der Tabelle im Backend | DocumentId of the data record in the table in the backend
          example: 110000000404
        eventName:
          type: string
          description: Name des Events | Name of the event
          example: START_DEFINITION_ZAEHLZEIT
        code:
          type: string
          description: Code für die Zählzeit | Code for the metering time
          example: ABC
        beginndatum:
          type: string
          format: date-time
          description: Beginndatum der Zählzeit | Start date of the metering time
          example: '2024-06-30T22:00:00Z'
        endedatum:
          type: string
          format: date-time
          description: Enddatum der Zählzeit | End date of the metering time
          example: '2024-08-30T22:00:00Z'
        haeufigkeit:
          type: string
          description: Häufigkeit der Zählzeit | Frequency of the metering time
          example: JAEHRLICH
      required:
        - id, eventName, code, beginndatum, endedatum, haeufigkeit
    START_KUENDIGUNG:
      type: object
      description: Schema für die Kündigung eines Vertrags | Schema for the termination of a contract
      properties:
        id:
          type: string
          description: BelegId des Datensatzes in der Tabelle im Backend | DocumentId of the data record in the table in the backend
          example: 110000000605
        eventName:
          type: string
          description: Name des Events | Name of the event
          example: START_KUENDIGUNG
        marktlokationsId:
          type: string
          description: Marktlokations-ID | Market location ID
          example: '50074561188'
        sparte:
          type: string
          description: Sparte, z.B. Gas | Sector, e.g., gas
          example: GAS
        vertragsart:
          type: string
          description: Art des Vertrags | Type of contract
          example: ENERGIELIEFERVERTRAG
        vertragsende:
          type: string
          format: date-time
          description: Ende des Vertrags | End of the contract
          example: '2024-06-01T04:00:00Z'
        empfaenger:
          type: string
          description: Rollencodenummer des Empfängers | Role code number of the recipient
          example: '9870013800007'
        absender:
          type: string
          description: Rollencodenummer des Absenders | Role code number of the sender
          example: '9800044300007'
      required:
        - id, eventName, marktlokationsId, sparte, vertragsart, vertragsende, empfaenger, absender
    EVENT_MIT_BELEGID:
      type: object
      description: Generisches Schema für Events, die eine BelegID erfordern | Generic schema for events that require a DocumentID
      properties:
        id:
          type: string
          description: BelegId des Datensatzes in der Tabelle im Backend | DocumentId of the data record in the table in the backend
          example: '110000000500'
        eventName:
          type: string
          description: Name des Events | Name of the event
          example: START_LIEFERBEGINN
          enum:
            - START_LIEFERBEGINN
            - START_ABR_NN
            - START_DEFINITION_SCHALTZEIT
            - START_DEFINITION_LEISTUNGSKURVE
            - START_DEFINITION_ZÄHLZEIT
            - START_KUENDIGUNG
            - START_ERHEBUNG_MESSWERTE
            - START_AEND_MALO_STRUKTUR_LF
            - START_AEND_NNA_MALO
            - START_AEND_ABR_BLINDARBEIT
            - START_AEND_PROGNOSEGRUNDLAGE
            - START_BILA_REL_AEND_VON_NB_MIT_ABHAENGIGK
            - START_N_BILA_REL_AEND_VON_NB
            - START_N_BILA_REL_AEND_VON_LF
            - START_N_BILA_REL_ANFR_ABR_BLINDARBEIT_AN_LF
            - START_BILA_REL_ANFR_AN_LF
            - START_N_BILA_REL_ANFR_AN_LF
            - START_N_BILA_REL_ANFR_AN_MSB_OHNE_ABHAENGIGK
            - START_ANFR_AN_MSB_MIT_ABHAENGIGK
            - START_BESTELLUNG_ZAEHLZEITDEFINITION
            - START_BESTELLUNG_ANGEBOT_KONFIGURATION
            - START_BESTELLUNG_KONFIGURATION
            - START_VERSAND_STORNO_MSCONS
            - START_VERSAND_LIEFERSCHEIN
            - START_VERSAND_COMDIS
            - START_LIEFERENDE
            - START_UEBERSICHT_ZAEHLZEITDEF
            - START_UEBERSICHT_SCHALTZEITDEF
            - START_UEBERSICHT_LEISTUNGSKURVENDEF
            - START_ANFRAGE_STAMMDATEN_MALO
            - START_ANFRAGE_MESSWERTE
            - START_ANFRAGE_STAMMDATEN_TRANCHE
            - START_EOG
            - START_VERSAND_BEENDIGUNG_AGV
            - START_VERSAND_ANF_STORNO
            - START_PREISBLATT
            - START_LIEFERBEGINN
            - START_AUFTRAGSSTATUS
            - START_ANFRAGE_STAMMDATENAENDERUNG
            - START_UEBERM_DEFINITION
      required:
        - id, eventName
    START_LIEFERBEGINN:
      type: object
      description: Schema für Lieferbeginn | Schema for the delivery start
      properties:
        id:
          type: string
          description: BelegId des Datensatzes in der Tabelle im Backend | DocumentId of the data record in the table in the backend
          example: "110000000605"
        eventName:
          type: string
          default: 'START_LIEFERBEGINN'
      required:
        - id, eventName
    AENDERUNG_AD:
      type: object
      description: Schema für Änderung | Schema for the update of object
      properties:
        id:
          type: string
          description: BelegId des Datensatzes in der Tabelle im Backend | DocumentId of the data record in the table in the backend
          example: "110000000605"
        eventName:
          type: string
          default: 'AENDERUNG_AD'
      required:
        - id, eventName
    START_ENERGIEMENGE:
      type: object
      description: Schema für Energiemenge | Schema for the Energiemenge
      properties:
        id:
          type: string
          description: BelegId des Datensatzes in der Tabelle im Backend | DocumentId of the data record in the table in the backend
          example: "110000000605"
        eventName:
          type: string
          default: 'START_ENERGIEMENGE'
      required:
        - id, eventName
    START_ZAEHLERSTAND:
      type: object
      description: Schema für Zaehlerstand | Schema for the Zaehlerstand
      properties:
        id:
          type: string
          description: BelegId des Datensatzes in der Tabelle im Backend | DocumentId of the data record in the table in the backend
          example: "110000000605"
        eventName:
          type: string
          default: 'START_ZAEHLERSTAND'
      required:
        - id, eventName
    START_LASTGANG:
      type: object
      description: Schema für Lastgang | Schema for the lastgang
      properties:
        id:
          type: string
          description: BelegId des Datensatzes in der Tabelle im Backend | DocumentId of the data record in the table in the backend
          example: "110000000605"
        eventName:
          type: string
          default: 'START_LASTGANG'
      required:
        - id, eventName
    START_PARTIN:
      type: object
      description: Schema für partin | Schema for the partin
      properties:
        id:
          type: string
          description: BelegId des Datensatzes in der Tabelle im Backend | DocumentId of the data record in the table in the backend
          example: "110000000605"
        eventName:
          type: string
          default: 'START_PARTIN'
      required:
        - id, eventName
    START_NACHRICHTENEINGANG:
      type: object
      description: Schema für Nachrichteingang | Schema for the inbound message
      properties:
        id:
          type: string
          description: BelegId des Datensatzes in der Tabelle im Backend | DocumentId of the data record in the table in the backend
          example: "110000000605"
        eventName:
          type: string
          default: 'START_NACHRICHTENEINGANG'
      required:
        - id, eventName
  examples:
    START_SPERRAUFTRAG:
      summary: START_SPERRAUFTRAG Versand Sperrauftrag auslösen | Trigger shipping blocking order
      value:
        id: STARTSPERRAUFTRAG1
        eventName: START_SPERRAUFTRAG
        marktlokationsId: '50000083216'
        sparte: STROM
        absender: '9903790000002'
        empfaenger: '9900321000005'
    START_LIEFERBEGINN_STROM:
      summary: START_LIEFERBEGINN (Strom) Lieferbeginn in Sparte Strom auslösen | Trigger start of delivery in the electricity division
      value:
        id: 110000000408
        eventName: START_LIEFERBEGINN
        marktlokationsId: '50074561188'
        sparte: STROM
        energierichtung: AUSSP
        vertragsbeginn: '2024-09-30T22:00:00Z'
        absender: '9903790000002'
        empfaenger: '9900321000005'
    START_LIEFERBEGINN_GAS:
      summary: Beispiel für einen START_LIEFERBEGINN_GAS Event | Example for a START_LIEFERBEGINN_GAS event
      value:
        id: 110000000611
        eventName: START_LIEFERBEGINN
        marktlokationsId: '50074561188'
        sparte: GAS
        vertragsbeginn: '2024-06-01T04:00:00Z'
        absender: '9800044300007'
        empfaenger: '9870013800007'
    START_ABR_NN:
      summary: START_ABR_NN Versand Netznutzungsabrechnung auslösen | Trigger dispatch grid usage billing
      value:
        id: 110000000409
        eventName: START_ABR_NN
        marktlokationsId: '50074561188'
        sparte: STROM
        artikelId: '1-02-0-001'
        vertragsbeginn: '2024-10-31T23:00:00Z'
        absender: '9900321000005'
        empfaenger: '9903790000002'
    START_DEFINITION_SCHALTZEIT:
      summary: Beispiel für einen START_DEFINITION_SCHALTZEIT Event | Example for a START_DEFINITION_SCHALTZEIT event
      value:
        id: 110000000406
        eventName: START_DEFINITION_SCHALTZEIT
        code: AC
        beginndatum: '2024-06-30T22:00:00Z'
        endedatum: '2024-08-30T22:00:00Z'
        haeufigkeit: JAEHRLICH
        schalthandlung: LEISTUNG_AN
    START_DEFINITION_LEISTUNGSKURVE:
      summary: Beispiel für einen START_DEFINITION_LEISTUNGSKURVE Event | Example for a START_DEFINITION_LEISTUNGSKURVE event
      value:
        id: 110000000405
        eventName: START_DEFINITION_LEISTUNGSKURVE
        code: ABC
        beginndatum: '2024-06-30T22:00:00Z'
        endedatum: '2024-08-30T22:00:00Z'
        obererSchwellwert: 50
    START_DEFINITION_ZAEHLZEIT:
      summary: Beispiel für einen START_DEFINITION_ZAEHLZEIT Event | Example for a START_DEFINITION_ZAEHLZEIT event
      value:
        id: 110000000404
        eventName: START_DEFINITION_ZAEHLZEIT
        code: ABC
        beginndatum: '2024-06-30T22:00:00Z'
        endedatum: '2024-08-30T22:00:00Z'
        haeufigkeit: JAEHRLICH
    START_KUENDIGUNG:
      summary: Beispiel für einen START_KUENDIGUNG Event | Example for a START_KUENDIGUNG event
      value:
        id: 110000000500
        eventName: START_KUENDIGUNG
    START_LIEFERBEGINN:
      summary: Beispiel für einen START_KUENDIGUNG Event | Example for a START_KUENDIGUNG event
      value:
        id: "110000000605"
        eventName: "START_LIEFERBEGINN"
